package common

import (
	"html/template"
	"os"
	"path/filepath"
)

const header = `
<!DOCTYPE html>

<!-- =================================================================
Do not modify! This file is automatically generated by "generator.go".
Look into "templates" directory for changing HTML files.
================================================================== -->

`

type Generator struct {
	config *WebsiteGeneratorConfig
}

func NewGenerator() *Generator {
	return &Generator{
		config: &config.WebsiteGeneratorConfig,
	}
}

func (this *Generator) Generate() {
	if !this.config.Enabled {
		return
	}

	_, err := os.Stat(this.config.TemplatesDirectory)
	if err != nil {
		return
	}

	os.Mkdir(this.config.OutputDirectory, 0755)

	partials, err := template.ParseGlob(this.config.TemplatesDirectory +  "/partials/*.html")
	if err != nil {
		panic(err)
	}

	entries, err := os.ReadDir(this.config.TemplatesDirectory)
	if err != nil {
		panic(err)
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		f, err := os.Create(filepath.Join(this.config.OutputDirectory, entry.Name()))
		if err != nil {
			panic(err)
		}

		defer f.Close()

		templ, err := partials.Clone()
		if err != nil {
			panic(err)
		}

	   _, err = templ.ParseFiles(filepath.Join(this.config.TemplatesDirectory, entry.Name()))
		if err != nil {
			panic(err)
		}

		_, err = f.WriteString(header)
		if err != nil {
			panic(err)
		}

		err = templ.ExecuteTemplate(f, entry.Name(), nil)
		if err != nil {
			panic(err)
		}
	}
}
